# Generated by Django 4.2.2 on 2023-07-22 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_alter_details_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="details",
            name="category_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="product.category"
            ),
        ),
    ]
